### ISSUE TITLE
[Error] do_everything.sh

### ISSUE THREAD

**Issue by dshahrokhian** [axon-research/c3d-keras#6]
When running the script, I end-up getting the following error:
```
Traceback (most recent call last):
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/dani/Software/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for 'pool3/MaxPool3D' (op: 'MaxPool3D') with input shapes:
[?,1,4,28,256].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convert_caffe_model.py", line 121, in <module>
    main()
  File "convert_caffe_model.py", line 51, in main
    model = c3d_model.get_model(summary=True, backend=dim_ordering)
  File "/home/dani/Git/c3d-keras/c3d_model.py", line 36, in get_model
    border_mode='valid', name='pool3'))
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/keras/models.py", line 455, in add
    output_tensor = layer(self.outputs[0])
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 545, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/keras/layers/pooling.py", line 323, in call
    data_format=self.data_format)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/keras/layers/pooling.py", line 381, in _pooling_function
    padding, data_format, pool_mode='max')
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3055, in pool3d
    x = tf.nn.max_pool3d(x, pool_size, strides, padding=padding)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1625, in max_pool3d
    strides=strides, padding=padding, name=name)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/dani/Software/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 2 from 1 for 'pool3/MaxPool3D' (op: 'MaxPool3D') with input shapes: [?,1,4,28,256].
download_test_video.sh: line 4: youtube-dl: command not found
Using TensorFlow backend.
[Info] image_dim_order (from default ~/.keras/keras.json)=<function image_dim_ordering at 0x7f5a8ad332f0>
[Info] Using backend=<function image_dim_ordering at 0x7f5a8ad332f0>
[Info] Reading model architecture...
Traceback (most recent call last):
  File "test_model.py", line 225, in <module>
    main()
  File "test_model.py", line 136, in main
    model = model_from_json(open(model_json_filename, 'r').read())
FileNotFoundError: [Errno 2] No such file or directory: './models/sports1M_weights_tf.json'
```

I understand that there are certain problems inherent of using python3, but what about the rest? `youtube-dl` should be added as dependency. Where can I download  `sports1M_weights_tf.json`?

Thanks,
Dani

**Comment by dshahrokhian** [comment]
Nevermind, it was all a problem from using it with python 3. I solved it by changing the calls to `_image_dim_ordering` to `image_dim_ordering()`. The dependency `youtube-dl` still needs to be added tho: `sudo apt-get install youtube-dl`.

**Comment by dshahrokhian** [comment]
You also forgot about the dependencies `pydot-ng` and `graphviz`.

**Comment by chuckcho** [comment]
Thanks for your comments. Will incorporate those into README.
